import Head from 'next/head'
import Sidebar from '../../components/sidebar'
import Widgets from '../../components/Widgets'
import CommentModal from '../../components/CommentModal'
import { ArrowLeftIcon } from '@heroicons/react/outline'
import { useRouter } from 'next/router'
import Post from "../../components/Post"
import { useEffect, useState } from 'react'
import { onSnapshot,doc } from 'firebase/firestore'
import {db} from "../../firebase"

export default function PostPage({newsRes,randUsers}) {
    const router=useRouter();
    const {id} = router.query;
    const [post,setPost] = useState();

    useEffect(()=>{
        onSnapshot(doc(db,"posts",id), (snapshot)=>setPost(snapshot))
    },[db,id])
  return (
    <div>
      <Head>
        <title>Post page</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto '>
      { /* SIDEBAR*/ }
      <Sidebar/>

      {/* FEED */}
    <div className="xl:ml-[300px] border-l border-r xl:min-w-[625px] sm:ml-[73px] border-gray-200 flex-grow max-w-2xl">
        <div className="flex py-2 px-3 items-center space-x-2 sticky top-0 z-50 bg-white border-b border-gray-200">
            <div className='hoverEffect' onClick={()=>router.push("/")}>
                <ArrowLeftIcon className='h-5 '/>
                
            </div>
            <h2 className="text-lg sm:text-xl font-bold cursor-pointer">Go Back</h2>
        </div>
        <Post id={id} post={post}/>
        {/* {posts.map((post) => (
        <motion.div key={post.id} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:1}}>
            <Post key={post.id} post={post} />
        </motion.div>
        ))} */}
    </div>

      {/* widgets */}
      <Widgets newsRes={newsRes.articles} randUsers={randUsers.results}/>
      
      {/* Modal */}
      <CommentModal>
        
      </CommentModal>

      </main>
    </div>
    
  )

}
export async function getServerSideProps() {
  const newsRes = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json").then((res) => res.json());
  
  const randUsers= await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res) => res.json());
  return{
    props:{
    newsRes,randUsers,    
    }
  }
}