import Head from 'next/head'
import Sidebar from '../components/sidebar'
import Feed from '../components/Feed'
import Widgets from '../components/Widgets'


export default function Home({newsRes,randUsers}) {
  return (
    <div>
      <Head>
        <title>Twitter clone</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <main className='flex min-h-screen max-w-7xl mx-auto '>
      { /* SIDEBAR*/ }
      <Sidebar/>

      {/* FEED */}
      <Feed/>

      {/* widgets */}
      <Widgets newsRes={newsRes.articles} randUsers={randUsers.results}/>
      

      </main>
    </div>
    
  )

}
export async function getServerSideProps() {
  const newsRes = await fetch(`https://saurav.tech/NewsAPI/top-headlines/category/business/us.json`).then((res) => res.json());
  
  const randUsers= await fetch("https://randomuser.me/api/?results=30&inc=name,login,picture").then((res) => res.json());
  return{
    props:{
    newsRes,randUsers,    
    }
  }
}